### ISSUE TITLE
初期取得のエフェクトを取得するのに経験点を使う

### ISSUE THREAD

**Issue by taralever** [ksx0330/FVTT-DX3rd-System#7]
ワーディング、リザレクトやレネゲイドビーイングの自動取得エフェクトなど、本来取得に経験点が必要ないエフェクトにも経験点を使わないといけなくなっている

**Comment by ksx0330** [comment]
エフェクトにある経験点チェックボックスを2つとも解除すると、経験値算出に入りません。
